const request = require('supertest');
const app = require('../backend/server');
const pool = require('../backend/db');

describe('Support Ticket System API Tests', () => {
  let customerToken = '';
  let customerUserId = null;
  let anotherCustomerToken = '';
  let agentToken = '';
  let createdTicketId = null;

  beforeAll(async () => {
    // Seed or fetch test tokens from database
    try {
      // 1. Customer Login (John Customer - ID 1)
      const customerRes = await request(app)
        .post('/api/auth/login')
        .send({
          email: 'john@example.com',
          password: 'password123'
        });
      
      if (customerRes.status === 200) {
        customerToken = customerRes.body.token;
        customerUserId = customerRes.body.user.id;
      }

      // 2. Another Customer Login (Sarah Customer - ID 2)
      const sarahRes = await request(app)
        .post('/api/auth/login')
        .send({
          email: 'sarah@example.com',
          password: 'password123'
        });
      
      if (sarahRes.status === 200) {
        anotherCustomerToken = sarahRes.body.token;
      }

      // 3. Support Agent Login (Alex Agent - ID 3)
      const agentRes = await request(app)
        .post('/api/auth/login')
        .send({
          email: 'alex.agent@support.com',
          password: 'password123'
        });
      
      if (agentRes.status === 200) {
        agentToken = agentRes.body.token;
      }
    } catch (e) {
      console.log('Test setup error:', e.message);
    }
  });

  afterAll(async () => {
    await pool.end();
  });

  // 1. Authentication Tests
  describe('Authentication Endpoints', () => {
    test('POST /api/auth/login - valid login succeeds', async () => {
      const res = await request(app)
        .post('/api/auth/login')
        .send({
          email: 'john@example.com',
          password: 'password123'
        });

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty('token');
      expect(res.body.user).toHaveProperty('role', 'customer');
    });

    test('POST /api/auth/login - invalid password fails with 401', async () => {
      const res = await request(app)
        .post('/api/auth/login')
        .send({
          email: 'john@example.com',
          password: 'wrong_password_123'
        });

      expect(res.status).toBe(401);
      expect(res.body).toHaveProperty('error', 'Invalid email or password');
    });

    test('GET /api/tickets - unauthenticated request returns 401', async () => {
      const res = await request(app).get('/api/tickets');

      expect(res.status).toBe(401);
      expect(res.body).toHaveProperty('error', 'Authentication token required');
    });
  });

  // 2. Ticket API Tests
  describe('Ticket Management Endpoints', () => {
    test('POST /api/tickets - invalid ticket input returns 400', async () => {
      if (!customerToken) return;

      const res = await request(app)
        .post('/api/tickets')
        .set('Authorization', `Bearer ${customerToken}`)
        .send({
          subject: '',
          description: ''
        });

      expect(res.status).toBe(400);
      expect(res.body).toHaveProperty('error');
    });

    test('POST /api/tickets - ticket creation works for customer', async () => {
      if (!customerToken) return;

      const res = await request(app)
        .post('/api/tickets')
        .set('Authorization', `Bearer ${customerToken}`)
        .send({
          subject: 'Automated Test Ticket',
          description: 'This is a test ticket generated by Supertest suite.',
          priority: 'high'
        });

      expect(res.status).toBe(201);
      expect(res.body.ticket).toHaveProperty('id');
      expect(res.body.ticket.subject).toBe('Automated Test Ticket');
      createdTicketId = res.body.ticket.id;
    });

    test('GET /api/tickets/:id - customer cannot access another customer ticket (403)', async () => {
      if (!anotherCustomerToken || !createdTicketId) return;

      // Sarah trying to access John's ticket
      const res = await request(app)
        .get(`/api/tickets/${createdTicketId}`)
        .set('Authorization', `Bearer ${anotherCustomerToken}`);

      expect(res.status).toBe(403);
      expect(res.body).toHaveProperty('error');
    });

    test('GET /api/tickets/:id - non-existent ticket returns 404', async () => {
      if (!customerToken) return;

      const res = await request(app)
        .get('/api/tickets/9999999')
        .set('Authorization', `Bearer ${customerToken}`);

      expect(res.status).toBe(404);
      expect(res.body).toHaveProperty('error', 'Ticket not found');
    });

    test('PUT /api/tickets/:id - agent can update ticket status and priority', async () => {
      if (!agentToken || !createdTicketId) return;

      const res = await request(app)
        .put(`/api/tickets/${createdTicketId}`)
        .set('Authorization', `Bearer ${agentToken}`)
        .send({
          status: 'in_progress',
          priority: 'medium'
        });

      expect(res.status).toBe(200);
      expect(res.body.ticket.status).toBe('in_progress');
      expect(res.body.ticket.priority).toBe('medium');
    });

    test('PUT /api/tickets/:id - customer cannot update ticket (403)', async () => {
      if (!customerToken || !createdTicketId) return;

      const res = await request(app)
        .put(`/api/tickets/${createdTicketId}`)
        .set('Authorization', `Bearer ${customerToken}`)
        .send({
          status: 'closed'
        });

      expect(res.status).toBe(403);
    });
  });
});
